pipeline {
    agent any

    environment {
        SPLUNK_HEC_URL = 'https://127.0.0.1:8088/services/collector/event'
        SPLUNK_HEC_TOKEN = credentials('3366c860-b822-4ee9-8cfe-398871d88cc5')
        SPLUNK_INDEX = 'vite_logs'
        GIT_REPO_URL = 'https://github.com/Samhitha1705/splunkvite.git'
        //REPO_DIR = 'splunkvite' // folder name after cloning
    }

    stages {
        stage('Checkout') {
            steps {
                // Uses Jenkins built-in Git support
                git url: "${env.GIT_REPO_URL}"
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${env.REPO_DIR}") {
                    bat "npm install"
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    dir("${env.REPO_DIR}") {
                        def packageJson = readJSON file: 'package.json'
                        if (packageJson.scripts?.test) {
                            bat "npm test"
                        } else {
                            echo 'No test script defined in package.json'
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Deploying to production..."
                    bat """
                        curl -k -X POST "${env.SPLUNK_HEC_URL}" ^
                        -H "Authorization: Splunk ${env.SPLUNK_HEC_TOKEN}" ^
                        -H "Content-Type: application/json" ^
                        -d "{\\"event\\": \\"Deployment Started\\", \\"sourcetype\\": \\"frontend_files\\", \\"index\\": \\"${env.SPLUNK_INDEX}\\"}"
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
