pipeline {
    agent any

    environment {
        SPLUNK_HEC_URL = 'https://127.0.0.1:8088/services/collector/event'
        SPLUNK_HEC_TOKEN = credentials('3366c860-b822-4ee9-8cfe-398871d88cc5')
        SPLUNK_INDEX = 'vite_logs'
    }

    stages {

        stage('Install Dependencies') {
            steps {
                bat "npm install"
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    def packageJson = readJSON file: 'package.json'
                    if (packageJson.scripts?.test) {
                        bat "npm test"
                    } else {
                        echo 'No test script defined in package.json'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Deploying to production..."
                    bat """
                        curl -k -X POST "${env.SPLUNK_HEC_URL}" ^
                        -H "Authorization: Splunk ${env.SPLUNK_HEC_TOKEN}" ^
                        -H "Content-Type: application/json" ^
                        -d "{\\"event\\": \\"Deployment Started\\", \\"sourcetype\\": \\"frontend_files\\", \\"index\\": \\"${env.SPLUNK_INDEX}\\"}"
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
